name: GitHub Pages Deploy Action

on:
  workflow_run:
    workflows: ["Build OS"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget graphviz

      - name: Install Doxygen
        run: |
          DOXY_VER="1.16.1"
          TRANSFORMED_VER=$(echo "$DOXY_VER" | tr '.' '_')
          wget https://github.com/doxygen/doxygen/releases/download/Release_${TRANSFORMED_VER}/doxygen-${DOXY_VER}.linux.bin.tar.gz
          tar -xzf doxygen-${DOXY_VER}.linux.bin.tar.gz
          sudo mv doxygen-${DOXY_VER}/bin/doxygen /usr/local/bin/doxygen

      - name: Generate Doxygen Documentation
        run: doxygen scripts/Doxyfile

      - name: Create .nojekyll
        run: touch docs/html/.nojekyll

      - name: Download disk-image artifact
        uses: actions/download-artifact@v4
        with:
          name: disk-image-grub
          path: temp_artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Demo Folder
        run: |
          mkdir -p docs/html/demo
          cp -r scripts/v86/* docs/html/demo/
          cp temp_artifact/disk.bin docs/html/demo/
          
          # Verify file structure (optional, helpful for debugging logs)
          ls -R docs/html/demo

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/html
